{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-vsearch
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - vsearch
    - scikit-bio {{ scikit_bio }}
    - biom-format {{ biom_format }}
    - numpy
    - pandas {{ pandas }}
    - pyyaml
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2-feature-table {{ qiime2_epoch }}.*

test:
  commands:
    - py.test --pyargs q2_vsearch
    
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - q2-feature-table >={{ q2_feature_table }}
    - pytest

  imports:
    - q2_vsearch
    - qiime2.plugins.vsearch

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
